#ifndef _CONFIG_H_
#define _CONFIG_H_

#define ZMODEM_SEGMENTED_STREAMING

#define ZMODEM_O_BYTESIZE_WRITE
#define ZMODEM_O_BYTESIZE_CRC16
#define ZMODEM_O_BYTESIZE_CRC32

#define FILE_MAX_SZ 0x33FF0
#define FILE_MIN_SZ 0x7f

//#define DEBUG

#endif
